import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  slide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#c6f4ec',
  },
  homeHead: {
    fontSize: 20,
    color: 'green',
    fontWeight: 'bold',
  },
  homeSubHead: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  subHead: {
    fontSize: 13,
    marginTop: 30,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  homeDetail: {
    width: '93%',
    fontSize: 15,
    marginTop: 5,
    color: 'green',
    textAlign: 'center',
  },
  homeLogo: {
    width: 200,
    height: 200,
    marginVertical: 10,
    resizeMode: 'contain',
  },
  appStoreBut: {
    marginTop: 10,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 15,
    backgroundColor: 'black',
  },
  playStoreBut: {
    marginTop: 10,
    paddingRight: 10,
    borderRadius: 10,
    paddingVertical: 5,
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: 'black',
  },
  boldTxt: {
    fontSize: 20,
    color: 'white',
    fontWeight: 'bold',
  },
  whiteTxt: {
    color: 'white',
  },
  play: {
    width: 40,
    height: 40,
    marginRight: 10,
    resizeMode: 'contain',
  },
  apple: {
    width: 25,
    height: 25,
    marginRight: 10,
    resizeMode: 'contain',
  },
  videoIcon: {
    width: 40,
    height: 40,
    marginRight: 10,
    resizeMode: 'contain',
  },
  playVideoBut: {
    marginTop: 10,
    borderRadius: 10,
    paddingVertical: 2,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 45,
    backgroundColor: '#52c0fa',
  },
  playVideoBut2: {
    marginTop: 10,
    borderRadius: 10,
    marginVertical: 20,
    paddingVertical: 3,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 45,
    backgroundColor: '#815dd4',
  },
  agreementRow: {
    marginVertical: 20,
    alignItems: 'center',
    flexDirection: 'row',
  },
  agreeTxt: {
    fontSize: 13,
    marginLeft: 5,
    fontWeight: 'bold',
  },
  dot: {
    borderWidth: 1,
    borderColor: 'green',
    backgroundColor: '#c6f4ec',
  },
  dot1: {
    backgroundColor: 'green',
  },
  link: {
    fontSize: 15,
    color: 'blue',
    marginTop: 10,
  },
  next1: {
    marginTop: 10,
    color: 'white',
    borderRadius: 5,
    paddingVertical: 5,
    paddingHorizontal: 50,
    backgroundColor: 'silver',
  },
  next: {
    marginTop: 10,
    color: 'white',
    borderRadius: 5,
    paddingVertical: 5,
    paddingHorizontal: 50,
    backgroundColor: 'green',
  },
  nexTxt: {
    fontSize: 18,
    color: 'white',
  },
});
