import colors from '../Utils/color';
import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  slide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lightGreen,
  },
  cross: {
    width: 30,
    zIndex: 5,
    height: 30,
    margin: 20,
    alignSelf: "flex-end"
  },
  checkBox1: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: 'black',
  },
  tick: {
    width: 18,
    height: 18,
  },
  checkBox2: {
    width: 18,
    height: 18,
    borderWidth: 2,
    borderRadius: 3,
  },
  homeHead: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.greenish,
  },
  homeSubHead: {
    fontSize: 25,
    fontWeight: 'bold',
  },
  subHead: {
    fontSize: 13,
    marginTop: 30,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  homeDetail: {
    width: '93%',
    fontSize: 15,
    marginTop: 5,
    color: colors.green,
    textAlign: 'center',
  },
  darkGreenTxt: {
    width: '93%',
    fontSize: 15,
    marginTop: 5,
    textAlign: 'center',
    color: colors.darkGreen,
  },
  homeLogo: {
    width: 200,
    height: 200,
    marginVertical: 10,
    resizeMode: 'contain',
  },
  appStoreBut: {
    marginTop: 10,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 15,
    backgroundColor: colors.black,
  },
  playStoreBut: {
    marginTop: 10,
    paddingRight: 10,
    borderRadius: 10,
    paddingVertical: 5,
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: colors.black,
  },
  boldTxt: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
  },
  whiteTxt: {
    color: colors.white,
  },
  play: {
    width: 40,
    height: 40,
    marginRight: 10,
    resizeMode: 'contain',
  },
  apple: {
    width: 25,
    height: 25,
    marginRight: 10,
    resizeMode: 'contain',
  },
  videoIcon: {
    width: 40,
    height: 40,
    marginRight: 10,
    resizeMode: 'contain',
  },
  playVideoBut: {
    marginTop: 10,
    borderRadius: 10,
    paddingVertical: 2,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 45,
    backgroundColor: colors.skyBlue,
  },
  playVideoBut2: {
    marginTop: 10,
    borderRadius: 10,
    marginVertical: 20,
    paddingVertical: 3,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 45,
    backgroundColor: colors.purple,
  },
  agreementRow: {
    marginVertical: 20,
    alignItems: 'center',
    flexDirection: 'row',
  },
  agreeTxt: {
    fontSize: 13,
    marginLeft: 5,
    fontWeight: 'bold',
  },
  agreeHeadTxt: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  dot: {
    borderWidth: 1,
    borderColor: 'green',
    backgroundColor: colors.lightGreen,
  },
  dot1: {
    backgroundColor: colors.green,
  },
  link: {
    fontSize: 15,
    marginTop: 10,
    color: colors.blue,
  },
  next1: {
    marginTop: 10,
    borderRadius: 5,
    paddingVertical: 5,
    color: colors.white,
    paddingHorizontal: 50,
    backgroundColor: colors.silver,
  },
  next: {
    marginTop: 10,
    borderRadius: 5,
    paddingVertical: 5,
    color: colors.white,
    paddingHorizontal: 50,
    backgroundColor: colors.green,
  },
  nexTxt: {
    fontSize: 18,
    color: colors.white,
  },
});
